name: ML Demo - Train, Evaluate, and PR

on: [push]

jobs:
  train-and-create-pr:
    runs-on: ubuntu-latest
    
    steps:
    - uses: iterative/setup-cml@v1
    
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scikit-learn pandas matplotlib seaborn

    
    - name: Train and evaluate model
      run: python train_evaluate.py  # This should generate confusion_matrix.png and accuracy.txt
           
    - name: Create CML report
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cat accuracy.txt
        cat accuracy.txt > report.md
        echo '![](./confusion_matrix.png "Confusion Matrix")' >> report.md
        cml comment create report.md
