name: ML Demo - Train, Evaluate, and PR

on: [push]

jobs:
  train-and-create-pr:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scikit-learn pandas matplotlib seaborn
        npm install -g @dvcorg/cml
    
    - name: Train and evaluate model
      run: |
        python train_evaluate.py
        
    - name: Check for existing branch
      id: check_branch
      run: |
        if git ls-remote --heads origin new-branch | grep new-branch; then
          echo "Branch already exists"
          echo "::set-output name=branch_exists::true"
        else
          echo "Branch does not exist"
          echo "::set-output name=branch_exists::false"
        fi
    
    - name: Checkout to branch
      if: steps.check_branch.outputs.branch_exists == 'false'
      run: git checkout -b new-branch
    
    - name: Add and commit confusion matrix image and accuracy result
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add confusion_matrix.png accuracy.txt
        git commit -m "Add confusion matrix and accuracy results" || echo "No changes to commit"
    
    - name: Push changes
      if: steps.check_branch.outputs.branch_exists == 'false'
      run: git push origin new-branch
    
    - name: Publish confusion matrix
      run: |
        echo "![Confusion Matrix](confusion_matrix.png)" > report.md
        cat accuracy.txt >> report.md
        cml comment report.md
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Add accuracy to report
      run: |
        echo "## Model Accuracy" >> report.md
        cat accuracy.txt >> report.md

    - name: Commit and push if new branch
      if: steps.check_branch.outputs.branch_exists == 'false'
      run: |
        git add report.md confusion_matrix.png accuracy.txt
        git commit -m "Add confusion matrix and accuracy results"
        git push origin new-branch

    - name: Create Pull Request
      if: steps.check_branch.outputs.branch_exists == 'false'
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Send CML report as PR comment
      run: |
        cml-send-comment report.md
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
