name: ML Demo - Train and Evaluate

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scikit-learn pandas matplotlib seaborn
    
    - name: Train and evaluate model
      run: |
        python train_evaluate.py
    
    - name: Create report file
      run: |
        echo "## Model Evaluation Report" > report.md
        echo "![Confusion Matrix](./confusion_matrix.png)" >> report.md
        echo "\`\`\`" >> report.md
        cat accuracy.txt >> report.md
        echo "\`\`\`" >> report.md
    
    - name: Push report to new branch
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git checkout -b new-evaluation-report
        git add report.md confusion_matrix.png accuracy.txt
        git commit -m "Add evaluation report"
        git push origin new-evaluation-report
    
    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "new-evaluation-report"
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Model Evaluation Report"
        pr_body: ${{ env.accuracy_content }}

